[package]
name = "nnv-rs"
version = "0.1.0"
edition = "2018"

[lib]
name = "nnv_rs_py"
crate-type = ["cdylib"]

[dependencies]
bitvec = "*"
good_lp = {version = "^1.1.3", features = ["highs"], default-features = false }
highs = "^0.4"
indextree = "^4.3.1"
ndarray = {version = "^0.15.2", features = ["rayon"] }
ndarray-linalg = { git = "https://github.com/rust-ndarray/ndarray-linalg", features = ["openblas-system"] }
ndarray-stats = "^0.5.0"
num = "^0.4.0"
numpy = "^0.13.2"
pyo3 = "^0.13"
rand = "^0.8.4"
truncnorm = { git = "https://github.com/DrKwint/truncnorm-rs" }
shh = "^1.0.1"

[dev-dependencies]
quickcheck = "*"
quickcheck_macros = "*"
ndarray-rand = "*"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"