[package]
name = "nnv-rs"
version = "0.4.0"
edition = "2021"
description   = "Verification and Statistics on Deep Neural Networks"
readme        = "README.md"
repository    = "https://github.com/drkwint/nnv-rs"
license       = "MIT"
keywords      = ["ndarray", "statistics", "verification", "machine-learning", "deep-learning"]
categories    = ["algorithms", "simulation", "science"]
exclude = [
    ".github",
]

[lib]
name = "nnv_rs"
crate-type = ["lib"]

[dependencies]
approx = "^0.4.0"
env_logger = "0.9.0"
good_lp = {version = "^1.2.0", features = ["coin_cbc"] }
#highs = "^0.5.0"
itertools = "^0.10.1"
log = "^0.4"
ndarray = {version = "^0.15.2" }
ndarray-linalg = { version = "^0.14.0", features = ["openblas-system"] }
ndarray-stats = "^0.5.0"
num = "^0.4.0"
rand = "^0.8.4"
truncnorm = "^0.3.3"
shh = "^1.0.1"
ordered-float = "^2.8.0"

[dev-dependencies]
ndarray-rand = "^0.14.0"
proptest = "1.0.0"
proptest-derive = "0.2.0"
criterion = { version = "0.3", features = ["html_reports"] }
pprof = { version = "0.5", features = ["flamegraph", "criterion" ] }

[[bench]]
name = "my_benchmark"
harness = false

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["run-for-all", "precommit-hook", "run-cargo-check", "run-cargo-fmt"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"