[package]
name = "nnv-rs"
version = "0.1.0"
edition = "2018"
description   = "Verification and Statistics on Deep Neural Networks"
readme        = "README.md"
repository    = "https://github.com/drkwint/nnv-rs"
license       = "MIT"
keywords      = ["ndarray", "statistics", "verification", "machine learning"]
categories    = ["algorithms", "simulation", "science"]
exclude = [
    ".github",
]

[lib]
name = "nnv_rs"
crate-type = ["lib", "cdylib"]
test = true

[dependencies]
approx = "^0.4.0"
env_logger = "*"
# good_lp = {version = "^1.1.3", features = ["highs"], default-features = false }
good_lp = { git = "https://github.com/DrKwint/good_lp", features=["highs"], default-features = false }
highs = "^0.4"
itertools = "^0.10.1"
log = "0.4" # { version = "0.4", features = ["max_level_trace", "release_max_level_warn"] }
ndarray = {version = "^0.15.2", features = ["rayon"] }
ndarray-linalg = { version = "^0.14.0", features = ["openblas-system"] }
ndarray-stats = "^0.5.0"
num = "^0.4.0"
rand = "^0.8.4"
truncnorm = "^0.3.1"
shh = "^1.0.1"
ordered-float = "^2.8.0"

[dev-dependencies]
ndarray-rand = "^0.14.0"
proptest = "1.0.0"
proptest-derive = "0.2.0"
criterion = { version = "0.3", features = ["html_reports"] }
pprof = { version = "0.5", features = ["flamegraph", "criterion" ] }

[[bench]]
name = "my_benchmark"
harness = false

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["run-for-all", "precommit-hook", "run-cargo-check", "run-cargo-fmt"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
